### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by isabeln23**

### CODE REVIEW

**Comment by jungheejung** [comment]
* implements baseline correction for interval-related analyses
* allows for event designation

**Comment by jungheejung** [comment]
Still getting used to this patch mode. 

For the cell that had the following code
```
eda_epochs_BL = nk.epochs_create(eda_processed, 
                                 event_stim, 
                                 sampling_rate=spacetop_samplingrate, 
                                 epochs_start=0, 
                                 epochs_end=9,
                                 baseline_correction=True)
```
I believe we need to feed in eda_filters, which would be the baseline corrected & filtered signal. Do you agree? @isabeln23

**Comment by jungheejung** [comment]
@isabeln23 I notice that cell No 82 and cell No 86 are identical, but named different variables. 

`[82] eda_phasic_BL = nk.eda_eventrelated(eda_epochs_BL)
eda_phasic_BL`

`[86] eda_tonic_BL = nk.eda_eventrelated(eda_epochs_BL)
eda_tonic_BL`

Which one would be correct? Or is it fine to use both?

**Comment by isabeln23** [comment]
> @isabeln23 I notice that cell No 82 and cell No 86 are identical, but named different variables.
> 
> `[82] eda_phasic_BL = nk.eda_eventrelated(eda_epochs_BL) eda_phasic_BL`
> 
> `[86] eda_tonic_BL = nk.eda_eventrelated(eda_epochs_BL) eda_tonic_BL`
> 
> Which one would be correct? Or is it fine to use both?

@jungheejung thanks for noticing! cell no 86 should be the following: 
[86] eda_tonic_BL = nk.eda_intervalrelated(eda_epochs_BL) eda_tonic_BL`
however, running these cells is only necessary if we wanted to do a baseline correction for the epochs (then we get these same onset times) - but yesterday we decided it is not necessary. I should have deleted these cells before uploading the code!

**Comment by jungheejung** [comment]
Awesome, thanks for confirming! @isabeln23

**Pull request merged**
